-- MySQL Workbench에서 EER Diagram 생성용 스크립트
-- 이 스크립트를 MySQL Workbench에서 실행하면 EER Diagram이 자동 생성됨

-- 데이터베이스 선택
USE AIRLINE;

-- 모든 테이블 정보 조회 (EER Diagram 생성 확인용)
SELECT 
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'AIRLINE'
ORDER BY TABLE_NAME;

-- 외래키 관계 확인
SELECT 
    tc.TABLE_NAME,
    kcu.COLUMN_NAME,
    kcu.REFERENCED_TABLE_NAME,
    kcu.REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
    ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
    AND tc.TABLE_SCHEMA = kcu.TABLE_SCHEMA
WHERE tc.TABLE_SCHEMA = 'AIRLINE'
    AND tc.CONSTRAINT_TYPE = 'FOREIGN KEY'
ORDER BY tc.TABLE_NAME;

